// utils/pdfGenerator.js

const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

/**
 * Generates a PDF buffer for a grade report.
 *
 * @param {Array} grades - Array of grade objects populated with subject and exam details.
 * @param {Object} exam - The exam object containing exam details.
 * @param {Object} user - The student user object containing student details.
 * @returns {Promise<Buffer>} - A promise that resolves to the generated PDF buffer.
 */
const generateGradeReport = (grades, exam, user) => {
  return new Promise((resolve, reject) => {
    try {
      // Create a new PDF document with A4 size and margins
      const doc = new PDFDocument({ size: 'A4', margin: 50 });
      const buffers = [];
      
      // Collect the data chunks as the document is being generated
      doc.on('data', (chunk) => buffers.push(chunk));
      doc.on('end', () => {
        const pdfBuffer = Buffer.concat(buffers);
        resolve(pdfBuffer);
      });
      
      // Document Title
      doc.fontSize(20)
         .text('Grade Report', { align: 'center' })
         .moveDown();

      // Exam Details
      doc.fontSize(12)
         .text(`Exam Name: ${exam.name}`)
         .text(`Exam Type: ${exam.type}`)
         .text(`Exam Date: ${new Date(exam.date).toLocaleDateString()}`)
         .moveDown();

      // Student Details
      doc.fontSize(12)
         .text(`Student Name: ${user.name}`)
         // If available, you can add more student details such as roll number, class, etc.
         .moveDown();

      // Table Header for Grades
      doc.fontSize(14)
         .text('Grades:', { underline: true })
         .moveDown(0.5);

      // Define table column positions
      const tableTop = doc.y;
      const colXPositions = {
        serial: 50,
        subjectCode: 100,
        subjectName: 200,
        marks: 400,
        grade: 450,
      };

      // Table header row
      doc.fontSize(12)
         .text('S.No', colXPositions.serial, tableTop)
         .text('Subject Code', colXPositions.subjectCode, tableTop)
         .text('Subject Name', colXPositions.subjectName, tableTop)
         .text('Marks', colXPositions.marks, tableTop, { align: 'right' })
         .text('Grade', colXPositions.grade, tableTop, { align: 'right' })
         .moveDown();

      // Draw a horizontal line below the header (optional)
      const headerBottomY = doc.y;
      doc.moveTo(50, headerBottomY)
         .lineTo(550, headerBottomY)
         .stroke();

      // Loop through each grade and add it to the PDF
      grades.forEach((grade, index) => {
        const y = doc.y + 5; // add a little spacing before each row

        doc.fontSize(12)
           .text(index + 1, colXPositions.serial, y)
           .text(grade.subject.code, colXPositions.subjectCode, y)
           .text(grade.subject.name, colXPositions.subjectName, y)
           .text(grade.marks.toString(), colXPositions.marks, y, { align: 'right' })
           .text(grade.grade, colXPositions.grade, y, { align: 'right' });
        doc.moveDown();
      });

      // Footer (optional)
      doc.moveDown();
      doc.fontSize(10)
         .text('Generated by ERP System', { align: 'center' });

      // Finalize the PDF and end the document
      doc.end();
    } catch (error) {
      reject(error);
    }
  });
};

const generatePayrollPDF = async (data, type) => {
    const doc = new PDFDocument();
    const logoPath = path.join(__dirname, '../assets/logo.png');

    // Add letterhead
    doc.image(logoPath, 50, 45, { width: 50 })
       .fontSize(20)
       .text('School Name', 110, 50)
       .fontSize(10)
       .text('Address: 123 School Street, City')
       .text('Phone: +1234567890, Email: info@school.com')
       .moveDown();

    if (type === 'monthly') {
        generateMonthlyPayrollPDF(doc, data);
    } else if (type === 'yearly') {
        generateYearlyPayrollPDF(doc, data);
    } else if (type === 'individual') {
        generateIndividualPayrollPDF(doc, data);
    }

    return doc;
};

const generateMonthlyPayrollPDF = (doc, data) => {
    // Add title
    doc.fontSize(16)
       .text(`Monthly Payroll Report - ${data.month} ${data.year}`, { align: 'center' })
       .moveDown();

    // Add table headers
    const headers = ['Staff Name', 'Basic Pay', 'Allowances', 'Deductions', 'Net Pay'];
    let y = doc.y;
    headers.forEach((header, i) => {
        doc.text(header, 50 + (i * 100), y);
    });

    // Add data rows
    data.records.forEach(record => {
        y += 20;
        doc.text(record.staffName, 50, y)
           .text(`₹${record.basicPay}`, 150, y)
           .text(`₹${record.totalAllowances}`, 250, y)
           .text(`₹${record.totalDeductions}`, 350, y)
           .text(`₹${record.netPay}`, 450, y);
    });
};

// Add similar functions for yearly and individual reports
// ... rest of implementation ...

module.exports = { generateGradeReport, generatePayrollPDF };
