require('dotenv').config({ path: '../../.env' });
const mongoose = require('mongoose');
const Teacher = require('../../src/modules/staff/models/staffModel');
const Payroll = require('../../src/modules/finance/models/Payroll');

const generatePayrollData = (teacher, month, year) => {
    const basicPay = teacher.salary || Math.floor(Math.random() * 50000 + 30000);
    const allowances = {
        hra: Math.floor(basicPay * 0.4),
        da: Math.floor(basicPay * 0.1),
        travelAllowance: 3000,
        medicalAllowance: 2000
    };
    const deductions = {
        pf: Math.floor(basicPay * 0.12),
        tds: Math.floor(basicPay * 0.1),
        professionalTax: 200
    };

    const totalAllowances = Object.values(allowances).reduce((a, b) => a + b, 0);
    const totalDeductions = Object.values(deductions).reduce((a, b) => a + b, 0);
    const netPay = basicPay + totalAllowances - totalDeductions;

    return {
        staffId: teacher._id,
        staffName: teacher.name || `${teacher.firstName} ${teacher.lastName}`,
        month: typeof month === 'string' ? months.indexOf(month) + 1 : month,
        year,
        basicPay,
        allowances,
        deductions,
        totalAllowances,
        totalDeductions,
        netPay,
        status: 'pending', // Changed to lowercase to match enum
        paymentMode: null,
        paymentDate: null,
        remarks: 'Generated by seeder',
        isActive: true
    };
};

const months = [
    'January', 'February', 'March', 'April', 'May', 'June',
    'July', 'August', 'September', 'October', 'November', 'December'
];

const seedPayrollData = async () => {
    try {
        await mongoose.connect(process.env.MONGODB_URI);
        console.log('Connected to MongoDB');

        await Payroll.deleteMany({});
        console.log('Cleared existing payroll data');

        const teachers = await Teacher.find({ isActive: true });
        console.log(`Found ${teachers.length} active teachers`);

        const payrollRecords = [];

        // Generate last 6 months of payroll records
        for (const teacher of teachers) {
            for (let i = 0; i < 6; i++) {
                const date = new Date();
                date.setMonth(date.getMonth() - i);
                const month = date.getMonth() + 1; // Using number for month (1-12)
                const year = date.getFullYear();

                const payrollData = generatePayrollData(teacher, month, year);
                payrollRecords.push(payrollData);
            }
        }

        await Payroll.insertMany(payrollRecords);
        console.log(`Created ${payrollRecords.length} payroll records`);

        await mongoose.connection.close();
        console.log('Database connection closed');
        process.exit(0);
    } catch (error) {
        console.error('Error seeding payroll data:', error);
        process.exit(1);
    }
};

seedPayrollData();